akhodakivskiy/VimFx

- extension/locale/de/vimfx.properties
- extension/locale/el-GR/vimfx.properties
- extension/locale/en-US/vimfx.properties
- extension/locale/hu/vimfx.properties
- extension/locale/id/vimfx.properties
- extension/locale/it/vimfx.properties
- extension/locale/ja/vimfx.properties
- extension/locale/nl/vimfx.properties
- extension/locale/pl/vimfx.properties
- extension/locale/ru/vimfx.properties
- extension/locale/zh-CN/vimfx.properties
- extension/locale/zh-TW/vimfx.properties
- extension/packages/commands.coffee
Propose new tab commands:
- Pin/unpin tab
- Duplicate current tab
- Close tabs from current tab to the end
- Close other tabs except the current tab
No sure what bindings should be associated.
Related issue: #121
> propose new tab commands

- README.md
Changed keyboard shortcut of __Insert Mode - Return to Normal__ mode from old _c-escape_ to _s-escape_
> Changed c-escape to s-escape

- extension/lib/utils.coffee
> Fix comment typo in utils.coffee

- extension/locale/fr/description
- extension/locale/fr/options.dtd
- extension/locale/fr/vimfx.properties
Hello :-)
Here is a French translation of VimFx, based on the `develop` branch.
> Added a french translation (v2)

- CONTRIBUTING.md
Sorry if it's a "too short" pull request - I thought creating an issue out of this would be even more disproportionate. :)
> Fixed a small but vital typo

- extension/locale/pt-BR/description
- extension/locale/pt-BR/vimfx.properties
I took the liberty to include a `vimfx.pot` file to help translators to use PO tools such as POEdit or Gtranslator.
Also I include a `pt-BR.po` file to help me translate and others later.
I use the [Translator Toolkit](http://translate-toolkit.readthedocs.org/en/latest/index.html) which helps me convert from `.properties` to `.po`.
For reference check this out <http://translate-toolkit.readthedocs.org/en/latest/commands/prop2po.html>
As an open source project, I suggest you start using Transifex to translate. It's free for open source projects and it's great.
> Translation to pt-BR.

- extension/locale/zh-TW/description
- extension/locale/zh-TW/vimfx.properties
> update zh-TW strings

- extension/locale/de/vimfx.properties
I tried to complete the file `extension/locale/de/vimfx.properties` since there were some English strings left in it.
> Patch for German translations

- extension/locale/fr/description
- extension/locale/fr/vimfx.properties
Hello,
I've updated the French translation :-)
Running `gulp sync-locales` indicates that the translation is only 99% complete but this is because the french for « documentation » is also « documentation ».
> Update the French translation

- extension/locale/de/vimfx.properties
Fixes typos. Uses passive voice where appropriate.
> Improves German locale

- extension/locale/it/vimfx.properties
This time on the right branch ;)
> Added italian translation.

- extension/locale/ru/vimfx.properties
I totally completed the Russian translation
> Update russian locale

- documentation/api.md
- documentation/button.md
- extension/lib/events-frame.coffee
- extension/lib/events.coffee
- extension/lib/main.coffee
- extension/lib/utils.coffee
- extension/lib/vim-frame.coffee
- extension/lib/vim.coffee
- extension/skin/style.css
> Make the button grey in "Insert mode"

- documentation/commands.md
- extension/lib/commands-frame.coffee
- extension/lib/commands.coffee
- extension/lib/defaults.coffee
- extension/lib/events-frame.coffee
- extension/lib/events.coffee
- extension/lib/hints.coffee
- extension/lib/scrollable-elements.coffee
- extension/lib/utils.coffee
- extension/lib/vim-frame.coffee
- extension/lib/vim.coffee
- extension/locale/de/vimfx.properties
- extension/locale/en-US/vimfx.properties
- extension/locale/fr/vimfx.properties
- extension/locale/id/vimfx.properties
- extension/locale/it/vimfx.properties
- extension/locale/ja/vimfx.properties
- extension/locale/nl/vimfx.properties
- extension/locale/pt-BR/vimfx.properties
- extension/locale/ru/vimfx.properties
- extension/locale/sv-SE/vimfx.properties
- extension/locale/zh-CN/vimfx.properties
- extension/locale/zh-TW/vimfx.properties
- extension/skin/style.css
> Add `zF` to click browser elements using hint markers

- extension/locale/es/vimfx.properties
> es locale update

- extension/locale/ja/vimfx.properties
> Update ja locale

- extension/locale/ru/vimfx.properties
> Update ru locale

- documentation/api.md
- documentation/commands.md
- documentation/options.md
Spotted some trivial mistakes while reading the documentation.
> Minor documentation fixes.

- extension/skin/style.css
with https://bugzilla.mozilla.org/show_bug.cgi?id=1035091
This closes #904.
> -moz-document gone

- extension/lib/markable-elements.coffee
- extension/lib/utils.coffee
This should fix #917 and #918.
(I don't know why this was missing for such a long time while it still worked for me....)
> export isXULDocument from utils and fix Ci.nsIDOMElement gone

- extension/lib/commands.coffee
- extension/lib/modes.coffee
- extension/lib/utils.coffee
Fix some more bugs found on 61 developer edition.
getFindBar() was changed to return a promise: https://bugzil.la/1358815
window.DeveloperToolbar was removed: https://bugzil.la/1382661
> Fix findBar and DeveloperToolbar.

- extension/lib/commands.coffee
This was recomended by the linter as indicated in #920.
> Use require instead of Cu.import.

- extension/lib/modes.coffee
> Fix calling part of utils getFindBar()

- extension/locale/es/vimfx.properties
> es locale update from en-US locale

- CHANGELOG.md
- PEOPLE.md
- README.md
- extension/install.rdf.tmpl
- extension/lib/commands.coffee
- extension/lib/help.coffee
- extension/lib/main.coffee
- extension/lib/options.coffee
- extension/lib/prefs.coffee
- extension/lib/vim.coffee
- extension/options.js
- extension/options.xhtml
- extension/options.xul
- extension/skin/options.css
- package.json
Sorry for yet another PR! The fx70 stuff should've gone into the last PR--this is my bad (my nightly wasn't up to date when testing). 
I'll also state again that I'm open to take over maintainership, as to not bother lydell with my PRs ;-) (that is of course unless lydell is fine with staying maintainer--I have no intention of staging a coup)
> More Firefox 70 fixes, the settings are back
